/**
 * Injected Script - Runs in page context to access Qlik APIs
 * Uses Capability API + enigma.js for advanced operations
 */

interface QlikRequest {
  id: string;
  action: string;
  payload: Record<string, unknown>;
}

let qlik: any = null;
let enigmaLib: any = null;
let enigmaSession: any = null;
let enigmaGlobal: any = null;
let enigmaApp: any = null;

// Load Qlik Capability API via RequireJS
function loadQlik(): Promise<any> {
  return new Promise((resolve, reject) => {
    if (qlik) {
      resolve(qlik);
      return;
    }
    const req = (window as any).require;
    if (!req) {
      reject(new Error("RequireJS not available"));
      return;
    }
    req(["qlik"], (q: any) => {
      qlik = q;
      console.log("[qlik-mcp] Qlik Capability API loaded");
      resolve(q);
    }, (err: any) => {
      reject(new Error("Failed to load Qlik: " + err));
    });
  });
}

// Load enigma.js library via RequireJS
function loadEnigmaLib(): Promise<any> {
  return new Promise((resolve, reject) => {
    if (enigmaLib) {
      resolve(enigmaLib);
      return;
    }
    const req = (window as any).require;
    if (!req) {
      reject(new Error("RequireJS not available"));
      return;
    }
    // Try loading enigma.js from Qlik's bundled version
    req(["enigma"], (e: any) => {
      enigmaLib = e;
      console.log("[qlik-mcp] enigma.js library loaded");
      resolve(e);
    }, () => {
      // Fallback: use Capability API internals
      console.log("[qlik-mcp] enigma.js not available, using fallback");
      resolve(null);
    });
  });
}

// Get WebSocket URL from current page
function getWebSocketUrl(): string {
  const loc = window.location;
  const protocol = loc.protocol === "https:" ? "wss:" : "ws:";
  const appMatch = loc.pathname.match(/\/app\/([a-zA-Z0-9-]+)/);
  const appId = appMatch ? appMatch[1] : "";
  // Handle virtual proxy
  const pathParts = loc.pathname.split("/app/")[0];
  return `${protocol}//${loc.host}${pathParts}/app/${appId}`;
}

// Connect via enigma.js
async function connectEnigma(): Promise<any> {
  if (enigmaApp) return enigmaApp;

  await loadEnigmaLib();

  // Try to get enigma model from Capability API internal
  if (qlik) {
    const capApp = qlik.currApp?.();
    if (capApp) {
      // Check for internal enigma model
      const model = capApp.model || capApp.enigmaModel || capApp._enigmaModel;
      if (model) {
        enigmaApp = model;
        console.log("[qlik-mcp] Using Capability API internal enigma model");
        return enigmaApp;
      }
    }
  }

  // Direct enigma.js connection
  if (enigmaLib) {
    const wsUrl = getWebSocketUrl();
    const appMatch = window.location.pathname.match(/\/app\/([a-zA-Z0-9-]+)/);
    const appId = appMatch ? appMatch[1] : "";

    try {
      // Fetch schema
      const schemaResp = await fetch("/resources/autogenerated/qix/engineapi.json");
      const schema = await schemaResp.json();

      enigmaSession = await enigmaLib.create({
        schema,
        url: wsUrl,
        createSocket: (url: string) => new WebSocket(url)
      });

      enigmaGlobal = await enigmaSession.open();
      enigmaApp = await enigmaGlobal.openDoc(appId);
      console.log("[qlik-mcp] Connected via enigma.js");
      return enigmaApp;
    } catch (err) {
      console.error("[qlik-mcp] enigma.js connection failed:", err);
    }
  }

  return null;
}

// Get enigma app - tries multiple methods
async function getEnigmaApp(): Promise<any> {
  if (enigmaApp) return enigmaApp;
  return connectEnigma();
}

// Listen for requests from content script
window.addEventListener("qlik-mcp-request", async (event: Event) => {
  const detail = (event as CustomEvent<QlikRequest>).detail;
  const { id, action, payload } = detail;

  try {
    const result = await handleAction(action, payload);
    window.dispatchEvent(new CustomEvent("qlik-mcp-response", {
      detail: { id, result }
    }));
  } catch (err) {
    window.dispatchEvent(new CustomEvent("qlik-mcp-response", {
      detail: { id, error: (err as Error).message }
    }));
  }
});

async function handleAction(action: string, payload: Record<string, unknown>): Promise<unknown> {
  // Load Qlik via RequireJS if not already loaded
  if (!qlik && action !== "check-qlik") {
    await loadQlik();
  }

  if (!qlik && action !== "check-qlik") {
    throw new Error("Qlik APIs not available");
  }

  const app = qlik?.currApp?.();

  switch (action) {
    case "check-qlik":
      return { available: !!qlik, hasApp: !!app };

    case "get-status": {
      let appName = "";
      if (app) {
        try {
          const layout = await app.getAppLayout();
          appName = layout.qTitle;
        } catch { /* ignore */ }
      }
      return {
        available: !!qlik,
        hasApp: !!app,
        appId: app?.id,
        appName,
      };
    }

    case "list-apps":
      return new Promise((resolve) => {
        qlik.getAppList((list: any[]) => {
          resolve(list.map((a: any) => ({ id: a.qDocId, name: a.qTitle })));
        });
      });

    case "open-app":
      const openedApp = qlik.openApp(payload.appId as string);
      return { id: openedApp.id };

    case "get-sheets": {
      if (!app) throw new Error("No app open");
      try {
        // Try different methods to get sheets
        let sheets: any[] = [];

        // Method 1: app.getList
        try {
          const list = await app.getList("sheet");
          console.log("[qlik-mcp] getList result:", JSON.stringify(list).slice(0, 500));
          sheets = list?.qAppObjectList?.qItems || list?.layout?.qAppObjectList?.qItems || [];
        } catch (e) {
          console.log("[qlik-mcp] getList failed:", e);
        }

        // Method 2: createGenericObject with SheetList
        if (sheets.length === 0) {
          const sheetListObj = await app.createGenericObject({
            qInfo: { qType: "SheetList" },
            qAppObjectListDef: {
              qType: "sheet",
              qData: { title: "/qMetaDef/title", description: "/qMetaDef/description" }
            }
          });
          const layout = await sheetListObj.getLayout();
          console.log("[qlik-mcp] SheetList layout:", JSON.stringify(layout).slice(0, 500));
          sheets = (layout as any).qAppObjectList?.qItems || [];
          await app.destroySessionObject(sheetListObj.id);
        }

        return sheets.map((s: any) => ({
          id: s.qInfo?.qId,
          title: s.qData?.title || s.qMeta?.title || "Untitled",
          description: s.qData?.description || s.qMeta?.description || "",
        }));
      } catch (err) {
        console.error("[qlik-mcp] get-sheets error:", err);
        throw err;
      }
    }

    case "go-to-sheet":
    case "navigate-sheet":
      await qlik.navigation.gotoSheet(payload.sheetId as string);
      return { success: true };

    case "get-objects": {
      if (!app) throw new Error("No app open");
      try {
        // Get current sheet ID from URL
        const sheetMatch = window.location.href.match(/\/sheet\/([^\/]+)/);
        if (!sheetMatch) {
          throw new Error("Cannot determine current sheet from URL");
        }
        const sheetId = sheetMatch[1];

        // Get sheet object to find visualizations
        const sheetObj = await app.getObject(sheetId);
        const sheetLayout = await sheetObj.getLayout();
        console.log("[qlik-mcp] Sheet layout:", JSON.stringify(sheetLayout).slice(0, 1000));

        // Extract cells (visualizations) from sheet
        const cells = (sheetLayout as any).cells || (sheetLayout as any).qChildList?.qItems || [];
        const objects = cells.map((c: any) => ({
          id: c.name || c.qInfo?.qId,
          type: c.type || c.qInfo?.qType,
          bounds: c.bounds || { y: c.row, x: c.col, width: c.colspan, height: c.rowspan },
        }));

        return objects;
      } catch (err) {
        console.error("[qlik-mcp] get-objects error:", err);
        throw err;
      }
    }

    case "get-selections": {
      if (!app) throw new Error("No app open");
      try {
        const selObj = await app.createGenericObject({
          qInfo: { qType: "SelectionObject" },
          qSelectionObjectDef: {}
        });
        const selLayout = await selObj.getLayout() as any;
        console.log("[qlik-mcp] Selection layout:", JSON.stringify(selLayout).slice(0, 500));
        const selections = selLayout.qSelectionObject?.qSelections || [];
        await app.destroySessionObject(selObj.id);
        // Return shape expected by server: { fields: [...] }
        return {
          fields: Array.isArray(selections) ? selections.map((s: any) => ({
            fieldName: s.qField,
            selectedCount: s.qSelectedCount || 0,
            totalCount: s.qTotal || 0,
            selections: s.qSelectedFieldSelectionInfo?.map((i: any) => i.qName) || [],
          })) : []
        };
      } catch (err) {
        console.error("[qlik-mcp] get-selections error:", err);
        throw err;
      }
    }

    case "select":
    case "select-values": {
      if (!app) throw new Error("No app open");
      const fieldName = payload.fieldName as string;
      const valuesToSelect = (payload.values as any[]).map(v => String(v));
      console.log("[qlik-mcp] Selecting in field:", fieldName, "values:", valuesToSelect);

      // Create ListObject to find and select values
      const listObj = await app.createGenericObject({
        qInfo: { qType: "SelectionList" },
        qListObjectDef: {
          qDef: { qFieldDefs: [fieldName] },
          qInitialDataFetch: [{ qTop: 0, qLeft: 0, qWidth: 1, qHeight: 10000 }]
        }
      });
      const listLayout = await listObj.getLayout() as any;
      const matrix = listLayout.qListObject?.qDataPages?.[0]?.qMatrix || [];

      // Find element numbers for values to select
      const elemNumbers: number[] = [];
      for (const row of matrix) {
        if (valuesToSelect.includes(String(row[0]?.qText))) {
          elemNumbers.push(row[0].qElemNumber);
        }
      }

      console.log("[qlik-mcp] Found elemNumbers:", elemNumbers);

      if (elemNumbers.length > 0) {
        await listObj.selectListObjectValues("/qListObjectDef", elemNumbers, false);
      }

      await app.destroySessionObject(listObj.id);
      return { success: true, field: fieldName, selected: elemNumbers.length };
    }

    case "clear-field":
      if (!app) throw new Error("No app open");
      await app.field(payload.fieldName as string).clear();
      return { success: true };

    case "clear-all":
      if (!app) throw new Error("No app open");
      await app.clearAll();
      return { success: true };

    case "get-field-values": {
      if (!app) throw new Error("No app open");
      try {
        // Use createGenericObject with ListObjectDef for field values
        const listObj = await app.createGenericObject({
          qInfo: { qType: "FieldValueList" },
          qListObjectDef: {
            qDef: { qFieldDefs: [payload.fieldName as string] },
            qInitialDataFetch: [{ qTop: 0, qLeft: 0, qWidth: 1, qHeight: payload.maxValues as number || 100 }]
          }
        });
        const layout = await listObj.getLayout() as any;
        console.log("[qlik-mcp] Field values layout:", JSON.stringify(layout).slice(0, 500));
        const matrix = layout.qListObject?.qDataPages?.[0]?.qMatrix || [];
        await app.destroySessionObject(listObj.id);
        return matrix.map((row: any) => row[0]?.qText).filter(Boolean);
      } catch (err) {
        console.error("[qlik-mcp] get-field-values error:", err);
        throw err;
      }
    }

    case "evaluate":
    case "evaluate-expression":
      if (!app) throw new Error("No app open");
      const evalObj = await app.createGenericObject({
        qInfo: { qType: "expression" },
        expression: { qValueExpression: { qExpr: payload.expression as string } }
      });
      const evalLayout = await evalObj.getLayout() as any;
      const result = evalLayout.expression;
      await app.destroySessionObject(evalObj.id);
      return result;

    case "get-data":
      if (!app) throw new Error("No app open");
      const obj = await app.getObject(payload.objectId as string);
      const layout = await obj.getLayout() as any;
      const hyperCubePath = layout.qHyperCube ? "/qHyperCubeDef" : "/qListObject";
      const pages = await obj.getHyperCubeData(hyperCubePath, [{
        qTop: 0, qLeft: 0, qWidth: 10, qHeight: payload.rows as number || 100
      }]);
      return { layout, data: pages };

    case "forward":
      if (!app) throw new Error("No app open");
      await app.forward();
      return { success: true };

    case "back":
      if (!app) throw new Error("No app open");
      await app.back();
      return { success: true };

    case "lock-field":
      if (!app) throw new Error("No app open");
      await app.field(payload.fieldName as string).lock();
      return { success: true };

    case "unlock-field":
      if (!app) throw new Error("No app open");
      await app.field(payload.fieldName as string).unlock();
      return { success: true };

    case "get-bookmarks": {
      if (!app) throw new Error("No app open");
      const bmListObj = await app.createGenericObject({
        qInfo: { qType: "BookmarkList" },
        qBookmarkListDef: { qType: "bookmark", qData: { title: "/qMetaDef/title", description: "/qMetaDef/description" } }
      });
      const bmLayout = await bmListObj.getLayout() as any;
      const bookmarks = bmLayout.qBookmarkList?.qItems || [];
      await app.destroySessionObject(bmListObj.id);
      return bookmarks.map((b: any) => ({
        id: b.qInfo?.qId,
        title: b.qData?.title || b.qMeta?.title || "Untitled",
        description: b.qData?.description || b.qMeta?.description || ""
      }));
    }

    case "apply-bookmark":
      if (!app) throw new Error("No app open");
      await app.bookmark.apply(payload.bookmarkId as string);
      return { success: true };

    case "create-bookmark":
      if (!app) throw new Error("No app open");
      const bm = await app.bookmark.create(payload.title as string, payload.description as string);
      return { id: bm.id };

    case "get-variables": {
      if (!app) throw new Error("No app open");
      const varListObj = await app.createGenericObject({
        qInfo: { qType: "VariableList" },
        qVariableListDef: { qType: "variable", qShowReserved: false, qShowConfig: false }
      });
      const varLayout = await varListObj.getLayout() as any;
      const vars = varLayout.qVariableList?.qItems || [];
      await app.destroySessionObject(varListObj.id);
      return vars.map((v: any) => ({
        name: v.qName,
        definition: v.qDefinition,
        value: v.qContent?.qString || ""
      }));
    }

    case "set-variable":
      if (!app) throw new Error("No app open");
      await app.variable.setStringValue(payload.name as string, payload.value as string);
      return { success: true };

    case "export":
    case "export-object":
      if (!app) throw new Error("No app open");
      const expObj = await app.getObject(payload.objectId as string);
      const expResult = await expObj.exportData(payload.format as string || "CSV_C");
      return { url: expResult.qUrl };

    case "take-screenshot":
      if (!app) throw new Error("No app open");
      // Screenshot requires visualization object - return placeholder for now
      return { imageData: "Screenshot not implemented - use browser screenshot" };

    // Data Model Tools
    case "get-fields": {
      if (!app) throw new Error("No app open");
      const fieldListObj = await app.createGenericObject({
        qInfo: { qType: "FieldList" },
        qFieldListDef: { qShowSystem: payload.includeSystem as boolean }
      });
      const fieldLayout = await fieldListObj.getLayout() as any;
      const fields = fieldLayout.qFieldList?.qItems || [];
      await app.destroySessionObject(fieldListObj.id);
      return fields.map((f: any) => ({
        name: f.qName,
        cardinal: f.qCardinal,
        tags: f.qTags,
        isSystem: f.qIsSystem
      }));
    }

    case "get-tables": {
      if (!app) throw new Error("No app open");
      const eApp = await getEnigmaApp();
      if (eApp?.getTablesAndKeys) {
        // enigma.js available
        try {
          const info = await eApp.getTablesAndKeys({}, {}, 0, true, false);
          console.log("[qlik-mcp] getTablesAndKeys result:", JSON.stringify(info).slice(0, 500));
          return (info.qtr || []).map((t: any) => ({
            name: t.qName,
            rows: t.qNoOfRows,
            fields: t.qFields?.length || 0,
            keyFields: t.qKeyFields?.length || 0
          }));
        } catch (e) {
          console.log("[qlik-mcp] getTablesAndKeys failed:", e);
        }
      }
      // Fallback: extract tables from field tags
      console.log("[qlik-mcp] Using fallback for get-tables");
      const fieldListObj = await app.createGenericObject({
        qInfo: { qType: "FieldList" },
        qFieldListDef: { qShowSystem: false }
      });
      const fieldLayout = await fieldListObj.getLayout() as any;
      const fields = fieldLayout.qFieldList?.qItems || [];
      await app.destroySessionObject(fieldListObj.id);

      // Extract unique table names from field srcTable tags
      const tableMap = new Map<string, { name: string; fieldCount: number }>();
      for (const f of fields) {
        const srcTables = f.qSrcTables || [];
        for (const tableName of srcTables) {
          if (!tableMap.has(tableName)) {
            tableMap.set(tableName, { name: tableName, fieldCount: 0 });
          }
          tableMap.get(tableName)!.fieldCount++;
        }
      }

      // If no srcTables info, just return field count info
      if (tableMap.size === 0) {
        return [{ name: "Data Model", rows: 0, fields: fields.length, keyFields: 0 }];
      }

      return Array.from(tableMap.values()).map(t => ({
        name: t.name,
        rows: 0, // Not available via this method
        fields: t.fieldCount,
        keyFields: 0
      }));
    }

    case "get-associations": {
      if (!app) throw new Error("No app open");
      const eApp = await getEnigmaApp();
      if (eApp?.getTablesAndKeys) {
        const info = await eApp.getTablesAndKeys({}, {}, 0, true, false);
        return (info.qk || []).map((k: any) => ({
          keyField: k.qKeyFields?.[0] || "unknown",
          table1: k.qTables?.[0] || "",
          table2: k.qTables?.[1] || ""
        }));
      }
      return []; // enigma.js not available
    }

    case "get-table-schema": {
      if (!app) throw new Error("No app open");
      const { tableName } = payload as any;
      const eApp = await getEnigmaApp();
      if (eApp?.getTablesAndKeys) {
        const info = await eApp.getTablesAndKeys({}, {}, 0, true, false);
        const table = (info.qtr || []).find((t: any) => t.qName === tableName);
        if (!table) throw new Error(`Table not found: ${tableName}`);
        return {
          name: table.qName,
          rows: table.qNoOfRows,
          fields: (table.qFields || []).map((f: any) => ({
            name: f.qName,
            distinct: f.qnDistinctValues || 0,
            type: f.qTags?.includes("$numeric") ? "numeric" : "text"
          }))
        };
      }
      throw new Error("enigma.js not available for table schema");
    }

    case "get-master-measures": {
      if (!app) throw new Error("No app open");
      const measuresObj = await app.createGenericObject({
        qInfo: { qType: "MeasureList" },
        qMeasureListDef: { qType: "measure", qData: { title: "/title", expression: "/qMeasure/qDef" } }
      });
      const measuresLayout = await measuresObj.getLayout() as any;
      const measures = measuresLayout.qMeasureList?.qItems || [];
      await app.destroySessionObject(measuresObj.id);
      return measures.map((m: any) => ({
        id: m.qInfo?.qId,
        title: m.qData?.title || m.qMeta?.title,
        expression: m.qData?.expression,
        description: m.qMeta?.description
      }));
    }

    case "get-master-dimensions": {
      if (!app) throw new Error("No app open");
      const dimsObj = await app.createGenericObject({
        qInfo: { qType: "DimensionList" },
        qDimensionListDef: { qType: "dimension", qData: { title: "/title", field: "/qDim/qFieldDefs" } }
      });
      const dimsLayout = await dimsObj.getLayout() as any;
      const dims = dimsLayout.qDimensionList?.qItems || [];
      await app.destroySessionObject(dimsObj.id);
      return dims.map((d: any) => ({
        id: d.qInfo?.qId,
        title: d.qData?.title || d.qMeta?.title,
        field: d.qData?.field?.[0],
        description: d.qMeta?.description
      }));
    }

    case "get-object-properties": {
      if (!app) throw new Error("No app open");
      const propObj = await app.getObject(payload.objectId as string);
      const props = await propObj.getProperties();
      return props;
    }

    case "get-script": {
      if (!app) throw new Error("No app open");
      const eApp = await getEnigmaApp();
      let script: any = null;

      if (eApp?.getScript) {
        script = await eApp.getScript();
        console.log("[qlik-mcp] getScript from enigma.js, type:", typeof script);
      } else if (app.getScript) {
        script = await app.getScript();
        console.log("[qlik-mcp] getScript from app, type:", typeof script);
      }

      if (script === null) {
        throw new Error("Script access not available");
      }

      // Handle different return types
      if (typeof script === "string") {
        return script;
      }
      if (script.qScript !== undefined) {
        return script.qScript;
      }
      if (script.script !== undefined) {
        return script.script;
      }
      // Return as JSON if unknown structure
      return JSON.stringify(script, null, 2);
    }

    // Analysis Tools
    case "get-top-n": {
      if (!app) throw new Error("No app open");
      const { dimension, expression, n, sort } = payload as any;
      const topObj = await app.createGenericObject({
        qInfo: { qType: "TopN" },
        qHyperCubeDef: {
          qDimensions: [{ qDef: { qFieldDefs: [dimension] } }],
          qMeasures: [{ qDef: { qDef: expression }, qSortBy: { qSortByNumeric: sort === "top" ? -1 : 1 } }],
          qInitialDataFetch: [{ qTop: 0, qLeft: 0, qWidth: 2, qHeight: n }],
          qInterColumnSortOrder: [1, 0]
        }
      });
      const topLayout = await topObj.getLayout() as any;
      const matrix = topLayout.qHyperCube?.qDataPages?.[0]?.qMatrix || [];
      await app.destroySessionObject(topObj.id);
      return matrix.map((row: any) => ({
        dimension: row[0]?.qText,
        value: row[1]?.qNum ?? row[1]?.qText
      }));
    }

    case "get-crosstab": {
      if (!app) throw new Error("No app open");
      const { rowDim, colDim, expr, maxRows, maxCols } = payload as any;
      const pivotObj = await app.createGenericObject({
        qInfo: { qType: "Pivot" },
        qHyperCubeDef: {
          qDimensions: [
            { qDef: { qFieldDefs: [rowDim] } },
            { qDef: { qFieldDefs: [colDim] } }
          ],
          qMeasures: [{ qDef: { qDef: expr } }],
          qInitialDataFetch: [{ qTop: 0, qLeft: 0, qWidth: maxCols + 1, qHeight: maxRows }],
          qMode: "P"
        }
      });
      const pivotLayout = await pivotObj.getLayout() as any;
      await app.destroySessionObject(pivotObj.id);
      // Simplified - return raw pivot data
      const pivotData = pivotLayout.qHyperCube?.qPivotDataPages?.[0] || {};
      const cols = (pivotData.qTop || []).map((c: any) => c.qText);
      const rows = (pivotData.qLeft || []).map((r: any, i: number) => ({
        label: r.qText,
        values: (pivotData.qData?.[i] || []).map((v: any) => v.qNum ?? v.qText)
      }));
      return { columns: cols, rows };
    }

    case "detect-duplicates": {
      if (!app) throw new Error("No app open");
      const { fields, minCount } = payload as any;
      const fieldExpr = fields.length > 1 ? fields.map((f: string) => `[${f}]`).join(" & '|' & ") : `[${fields[0]}]`;
      const dupObj = await app.createGenericObject({
        qInfo: { qType: "Duplicates" },
        qHyperCubeDef: {
          qDimensions: [{ qDef: { qFieldDefs: [fieldExpr] } }],
          qMeasures: [{ qDef: { qDef: "Count(1)" }, qSortBy: { qSortByNumeric: -1 } }],
          qInitialDataFetch: [{ qTop: 0, qLeft: 0, qWidth: 2, qHeight: 1000 }],
          qInterColumnSortOrder: [1, 0]
        }
      });
      const dupLayout = await dupObj.getLayout() as any;
      const matrix = dupLayout.qHyperCube?.qDataPages?.[0]?.qMatrix || [];
      await app.destroySessionObject(dupObj.id);
      return matrix
        .filter((row: any) => (row[1]?.qNum || 0) >= minCount)
        .map((row: any) => ({ value: row[0]?.qText, count: row[1]?.qNum }));
    }

    case "find-outliers": {
      if (!app) throw new Error("No app open");
      const { fieldName, dimension, method, threshold } = payload as any;
      // Get stats first
      const statsExprs = [`Min([${fieldName}])`, `Max([${fieldName}])`, `Avg([${fieldName}])`, `Stdev([${fieldName}])`, `Fractile([${fieldName}], 0.25)`, `Fractile([${fieldName}], 0.75)`];
      const statsObj = await app.createGenericObject({
        qInfo: { qType: "Stats" },
        stats: statsExprs.map(e => ({ qValueExpression: { qExpr: e } }))
      });
      const statsLayout = await statsObj.getLayout() as any;
      const [min, max, avg, stdev, q1, q3] = statsExprs.map((_, i) => parseFloat(statsLayout.stats?.[i]) || 0);
      await app.destroySessionObject(statsObj.id);

      const iqr = q3 - q1;
      const lowerBound = method === "iqr" ? q1 - threshold * iqr : avg - threshold * stdev;
      const upperBound = method === "iqr" ? q3 + threshold * iqr : avg + threshold * stdev;

      // Find outliers
      const outlierExpr = dimension ? dimension : `RowNo()`;
      const outlierObj = await app.createGenericObject({
        qInfo: { qType: "Outliers" },
        qHyperCubeDef: {
          qDimensions: [{ qDef: { qFieldDefs: [outlierExpr] } }],
          qMeasures: [{ qDef: { qDef: `[${fieldName}]` } }],
          qInitialDataFetch: [{ qTop: 0, qLeft: 0, qWidth: 2, qHeight: 1000 }]
        }
      });
      const outlierLayout = await outlierObj.getLayout() as any;
      const matrix = outlierLayout.qHyperCube?.qDataPages?.[0]?.qMatrix || [];
      await app.destroySessionObject(outlierObj.id);

      const outliers = matrix
        .filter((row: any) => {
          const val = row[1]?.qNum;
          return val !== undefined && (val < lowerBound || val > upperBound);
        })
        .map((row: any) => ({ dimension: row[0]?.qText, value: row[1]?.qNum }));

      return { stats: { min, max, avg, stdev, q1, q3, lowerBound, upperBound }, outliers };
    }

    case "select-by-expression": {
      if (!app) throw new Error("No app open");
      const { fieldName, expression } = payload as any;
      const field = app.field(fieldName);
      await field.selectValues([], false, false); // clear first
      await field.select(expression);
      const selInfo = await field.getData();
      return selInfo.qDataPages?.[0]?.qMatrix?.length || 0;
    }

    case "search-select": {
      if (!app) throw new Error("No app open");
      const { fieldName, searchTerm } = payload as any;
      const field = app.field(fieldName);
      await field.selectMatch(searchTerm, false);
      const selInfo = await field.getData();
      return selInfo.qDataPages?.[0]?.qMatrix?.filter((r: any) => r[0]?.qState === "S").length || 0;
    }

    case "get-ranking": {
      if (!app) throw new Error("No app open");
      const { dimension, expression, limit } = payload as any;
      const rankObj = await app.createGenericObject({
        qInfo: { qType: "Ranking" },
        qHyperCubeDef: {
          qDimensions: [{ qDef: { qFieldDefs: [dimension] } }],
          qMeasures: [{ qDef: { qDef: expression }, qSortBy: { qSortByNumeric: -1 } }],
          qInitialDataFetch: [{ qTop: 0, qLeft: 0, qWidth: 2, qHeight: limit || 100 }],
          qInterColumnSortOrder: [1, 0]
        }
      });
      const rankLayout = await rankObj.getLayout() as any;
      const matrix = rankLayout.qHyperCube?.qDataPages?.[0]?.qMatrix || [];
      await app.destroySessionObject(rankObj.id);
      return matrix.map((row: any, i: number) => ({
        rank: i + 1,
        dimension: row[0]?.qText,
        value: row[1]?.qNum ?? row[1]?.qText
      }));
    }

    default:
      throw new Error(`Unknown action: ${action}`);
  }
}

// Signal that injected script is ready
window.dispatchEvent(new CustomEvent("qlik-mcp-ready"));
console.log("[qlik-mcp] Injected script loaded");
